name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: prod  # Use the environment that has the AWS_REGION secret

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Generate Backend Config
        run: |
          echo 'terraform {
            backend "s3" {
              bucket = "${{ secrets.TF_STATE_BUCKET }}"
              key    = "${{ secrets.PROJECT_NAME }}/terraform.tfstate"
              region = "${{ secrets.AWS_REGION }}"
            }
          }' > backend.tf

      - name: Upload Backend Config to S3
        run: aws s3 cp backend.tf s3://${{ secrets.TF_STATE_BUCKET }}/${{ secrets.PROJECT_NAME }}/backend.tf

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve \
             -var="project_name=${{ secrets.PROJECT_NAME }}" \
             -var="tf_state_bucket=${{ secrets.TF_STATE_BUCKET }}"

      - name: Capture Outputs
        id: outputs
        run: |
          terraform output -json > /tmp/tf_outputs.json
          echo "s3_bucket_name=$(jq -r '.s3_bucket_name.value' /tmp/tf_outputs.json)"  >> $GITHUB_STATE
          echo "ftp_server_url=$(jq -r '.ftp_server_url.value' /tmp/tf_outputs.json)" >> $GITHUB_STATE
          echo "ftp_server_address=$(jq -r '.ftp_server_address.value' /tmp/tf_outputs.json)" >> $GITHUB_STATE
          echo "ftp_username=$(jq -r '.ftp_username.value' /tmp/tf_outputs.json)" >> $GITHUB_STATE
          echo "ftp_password=$(jq -r '.ftp_password.value' /tmp/tf_outputs.json)" >> $GITHUB_STATE

      - name: Output Results
        run: |
          echo "S3 Bucket Name: $s3_bucket_name" >> $GITHUB_OUTPUT
          echo "FTP Server URL: $ftp_server_url" >> $GITHUB_OUTPUT
          echo "FTP Server Address: $ftp_server_address" >> $GITHUB_OUTPUT
          echo "FTP Username: $ftp_username" >> $GITHUB_OUTPUT
          echo "FTP Password: $ftp_password" >> $GITHUB_OUTPUT
